### ISSUE TITLE
[ikc] Missing LwIP Install

### ISSUE THREAD

**Issue by ppenna** [nanvix/microkernel#177]
# Description

In the `contrib/makefile.install` we are missing the installation of the LwIP static library.

**Comment by Theldus** [comment]
Already fixed in `feature-lwip-openrisc` ;-)

**Comment by ppenna** [comment]
@Theldus it would be nice if we could patch unstable with this fix so. Otherwise TravisCI tests for OpenRISC will remain disabled.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
