### ISSUE TITLE
[ikc] Mailbox Search

### ISSUE THREAD

**Issue by ppenna** [nanvix/microkernel#189]
# Description

Currently, the `do_mailbox_open()` and `do_mailbox_create()` routines should traverse the mailbox table to check if the requested mailbox already exists. If so, we simply increment the reference count of this mailbox.

Since the search logic is the same, we shall provide an internal function to this job and call it from `do_mailbox_open()` and `do_mailbox_create()`.

**Comment by joaofel-u** [comment]
`return -1` is OK or should I define a new error and return it if didn't find the mailbox on `do_mailbox_search()`?
