### ISSUE TITLE
[ikc] Starvation When Multiplexing a Hardware Mailbox

### ISSUE THREAD

**Issue by ppenna** [nanvix/microkernel#232]
# Description

We have the following problem in the kernel, because `mailbox_aread()` in the HAL is a blocking function:

- Cluster A spawns two threads A.1 and A.2
- Thread A.1 and A.2 create two virtual mailboxes M.1 and M.2, respectively
- M.1 and M.2 are multiplexed on top of the hardware mailbox M
- Cluster B spawns a thread B.1
- Thread B.1 opens a connection to M.1
- Thread A.1 and A.2 try to read a message from M.1 and M.2, respectively
- Thread A.2 succeeds first and enters the kernel
- Thread A.2 receives a message in M and notices that it addresses M.1
- The message is stored in a kernel buffer
- A.2 loops and waits for a message to arrive  in M.2
- The message never arrives and everyone starves

**Comment by ppenna** [comment]
@joaovicentesouto can we close this?

**Comment by joaovicentesouto** [comment]
@ppenna Yes, we can. That issue affected the portal too but with the `communicator` and `active` abstractions, we solve both.
