### ISSUE TITLE
[ikc] Getting Cluster Number Locally

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/microkernel#249]
The current implementation of `kcluster_get_num` function request to the master core to recover the cluster number. However, we can do it locally, moving the call to be performed by the slave core since that function is thread-safe.

## Update

Moving this function to slave core responsibility, LibNanvix shows up errors coming from communication interfaces.
We do not know yet why and where the problem occurs. But it is probably because before we did the cache invalidate to request the syscall to master core and now, we do not do that invalidation.

Related Branch: `enhancement-processor-get-num`

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
