### ISSUE TITLE
[ikc] Get Node Number Locally

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/microkernel#250]
The current implementation of `knode_get_num` function request to the master core to recover the node number. However, we can do it locally, moving the call to be performed by the slave core since that function is thread-safe.

## Update

Moving this function to slave core responsibility, LibNanvix shows up errors coming from communication interfaces.
We do not know yet why and where the problem occurs. But it is probably because before we did the cache invalidate to request the syscall to master core and now, we do not do that invalidation.

Related Branch: `enhancement-processor-get-num`

**Comment by ppenna** [comment]
@hansb21 and @joaovicentesouto could you link the commits here? I'm gonna work on this... I'd say that communication is faillling because of this old scheme....

**Comment by joaovicentesouto** [comment]
The commits are [4c25f83](https://github.com/nanvix/microkernel/commit/4c25f83c470a3d71a3324b852a0527ba1dc8c805) and [d7a112c](https://github.com/nanvix/microkernel/commit/d7a112c8b769bd4387db234af8816b607602a397) on `enhancement-processor-get-num` branch.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
