### ISSUE TITLE
[ikc] Cumulative IOCTL counters

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/microkernel#260]
## Description

There are two types of IOCTL counters that can be accessed, global and specific counters.

### Global counters

Global counters record the operations of a given interface from the moment of the boot until the system is shut down. As a result, the increment of these counters is affected by the entire system, that is, they are shared between the system and the user.

The constants that access these counters are found at:
- [Mailbox Global Counters](https://github.com/nanvix/microkernel/blob/dev/include/nanvix/kernel/mailbox.h#L45-L50)
- [Portal Global Counters](https://github.com/nanvix/microkernel/blob/dev/include/nanvix/kernel/portal.h#L50-L55)
- [Sync Global Counters](https://github.com/nanvix/microkernel/blob/dev/include/nanvix/kernel/sync.h#L43-L48)

### Specific counters

Specific counters relate to the characteristics of a created or open communication resource. That is, when this resource is created, these counters are reset and incremented as communication operations are performed. However, the values ​​accessed are cumulative where the value in the counters is the sum of all previous operations on this resource.

The constants that access these counters are found at:
- [Mailbox Specific Counters](https://github.com/nanvix/microkernel/blob/dev/include/nanvix/kernel/mailbox.h#L43-L44)
- [Portal Specific Counters](https://github.com/nanvix/microkernel/blob/dev/include/nanvix/kernel/portal.h#L48-L49)
- [Sync Specific Counters](https://github.com/nanvix/microkernel/blob/dev/include/nanvix/kernel/sync.h#L42)

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
