### ISSUE TITLE
[ikc] Discard of IKC Messages for Unopened Resources

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/microkernel#268]
## Description

The current virtualization of IKC services discard messages of unopened resources by other open resources because the following behavior:

- Physical channels allow communication without know which resources are involved.
- When the receiver node receives a message that targets another resource, it searches in the resource table looking for the target resource. If the resource are not opened, the kernel discard the message.

Besides that, as an example, the kernel creates a slave thread (SHM snooper) that continuously reads from a mailbox waiting for requests or data. This thread can discard messages destined for the user.

## Fix

We need to be able to keep these preterm messages to not depend on explicit synchronization for user/kernel threads/nodes.

## Observation

This issue may exist in sync, but the fix needs to be made at the HAL level.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
