### ISSUE TITLE
[ikc] Increase IKC Structures Port Range

### ISSUE THREAD

**Issue by joaofel-u** [nanvix/microkernel#270]
# Description #
We should increase the IKC structures port range to permit the user to have a special range of ports for general purpose, not only the standard range which is used for addressing cluster cores running. In other words, we should increase the number of ports exported by the kernel for a single IKC structure.

# Related PRs #
This issue has started to be resolved in the PR #269 .

## Important Note ##
When this issue get solved,  we should fix the temporary workaround inserted in nanvix/multikernel#221 that reserves a small portion in the highest part of the standard ports range.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
