### ISSUE TITLE
[ikc] Widening IKC Ports Range breaks execution in MPPA-256

### ISSUE THREAD

**Issue by joaofel-u** [nanvix/microkernel#271]
# Related Issues #
- #270 - [[ikc] Increase IKC Structures Port Range](https://github.com/nanvix/microkernel/issues/270)

**Note:** This bug appeared when trying to solve the issue above in the PR #269.

# Description #
It appears that only increasing the number of ports exported by the kernel changing the kernel constants `MAILBOX_PORT_NR` and `KPORTAL_PORT_NR` doesn't have the desired effect. When resolving the problem this way, the execution in MPPA-256 fails during the Kernel IKC Tables Initialization and the execution freezes. It may be some hardcoded values in the implementation that aren't coping with the new value of the referred contants are broking the code syntax. Further information is required about this problem.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
