### ISSUE TITLE
[tm] Use IPI to stop one thread and schedule another

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/microkernel#280]
Currently, the thread manager only supports cooperative threads, that is, threads that need to voluntarily leave the core or terminate so that other threads can run.

Therefore, we must implement a scheduler centered on the master core that interrupts a core using IPI and changes the context of the thread.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
