### ISSUE TITLE
[ikc] Communicator IOCTL Operations Unification

### ISSUE THREAD

**Issue by joaofel-u** [nanvix/microkernel#295]
# Description #
For now, valid communicator IOCTL operations codes are defined both in ```nanvix/kernel/mailbox.h``` and ```nanvix/kernel/portal.h``` without any relationship, except for following the same definition order of ```src/kernel/noc/communicator.h```.

Instead, we should guarantee the conformation of these operation codes by setting the specific abstraction aliases to refer to these opcodes defined by the communicator generalization header.

Additionally, a new alias named ```MAILBOX/PORTAL_IOCTL_LAST_OP``` should be created for both abstractions, and be used to validate an IOCTL opcode parameter in the system entry function, instead of letting this verification to its underlying implementation.

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
