### ISSUE TITLE
[pm] Kernel's condvar, semaphore, and mutex have no destructive function

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/microkernel#299]
### Description

We must provide destructive functions to do sanity checks on synchronization abstractions when we will not use them anymore. For instance, we must ensure that no threads are waiting on a semaphore that will not be used again.

#### Create destructive functions (thread.h)
- [ ] `convar_destroy`
- [ ] `semaphore_destroy`
- [ ] `mutex_destroy`

**Comment by ppenna** [comment]
Closing this issue because the source tree was reset and it may now be invalid.
