### ISSUE TITLE
API Testing Units for Naming Service

### ISSUE THREAD

**Issue by ppenna** [nanvix/microkernel#6]
**Description**

The following API unit tests should be designed and implemented:

- [x] IO Cluster: Link and Unlink a Name (76b789b23bfab8cf2b996bcb9092a9b9e3cd3aee)
- [x] IO Cluster: Lookup a Name (76b789b23bfab8cf2b996bcb9092a9b9e3cd3aee)
- [x] Compute Cluster: Link and Unlink a Name (d8b077a72753bd843fd6f643348d22c5b779bb86)
- [x] Compute Cluster: Lookup a Name (4aab01797955980f1384c51ed2ec3d61117e9996)

**Comment by jordanjean** [comment]
All tests are successfully passed

**Comment by ppenna** [comment]
The following unit tests were introduced in 76b789b23bfab8cf2b996bcb9092a9b9e3cd3aee:

-  Register a Name on an IO Cluster
-  Lookup a Name on an IO Cluster
-  Remove a Name on IO Cluster

**Comment by jordanjean** [comment]
Now it is possible to get the NoC node ID in which a thread is running on, multithreaded tests on IO cluster should be designed and implemented.
